on: 

  push: 

    branches: [ dev ] 

    paths: 

    - 'Pylint-YML/Pylint/factorial.py' 

    - 'Pylint-YML/Pylint/lint.py' 
 

 jobs: 

  build: 

    runs-on: windows-latest 

    steps: 

    - uses: actions/checkout@v2 

    - name: Set up Python 3.9.9

      uses: actions/setup-go@v2.1.5 

      with: 

        python-version: 3.9.9

    - name: Install dependencies 

      run: | 

        python -m pip install --upgrade pip 

        pip install pylint 

     - name: Lint with pylint 

      run: | 


        python lint.py 
